apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Config
  - config/mongodb-configmap.yaml
  - config/mongodb-secret.yaml
  - config/mongodb-storage.yaml
  
  # Deployments and StatefulSets
  - deployments/mongodb-statefulset.yaml
  - deployments/url-shortener-deployment.yaml
  - deployments/url-shortener-hpa.yaml
  
  # Services and Ingress
  - services/mongodb-service.yaml
  - services/url-shortener-service.yaml
  - services/url-shortener-ingress.yaml 